# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Hyde
tagline: 'A Jekyll theme'
description: 'A brazen two‑column Jekyll theme…'
url: https://youngin3737.github.io
baseurl: ""

author:
  name: 'Mark Otto'
  url: https://twitter.com/mdo

# Plugins (GitHub Pages)
plugins:
  - jekyll-paginate

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/poole/hyde