# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: YoungIn Kim
tagline: 'A Jekyll theme'
description: 'M.S. student in HCIL (KAIST, SoC) Prof. Geehyuk Lee'
url: https://youngin3737.github.io
baseurl: ""

author:
  name: 'Mark Otto'
  url: https://twitter.com/mdo

# Plugins (GitHub Pages)
plugins:
  - jekyll-paginate

paginate: 5

github:
  repo: https://github.com/poole/hyde